### ISSUE TITLE
Package is not functional

### ISSUE THREAD

**Issue by fredcallaway** [shagabutdinov/sublime-autocompletion#6]
You refer to the package internally as Autocompletion but the external name is AutcompletionFuzzy. This results in an import error, as Autocompletion is not the name of a package. I was able to fix this by replacing all instances of "Autocompletion" with "AutocompletionFuzzy".

**Comment by shagabutdinov** [comment]
Fixed in f3b39fbcfbe6b03b317c207fdaca83819d0d096f
