### ISSUE TITLE
For other app

### ISSUE THREAD

**Issue by Alexey-T** [shagabutdinov/sublime-autocompletion#7]
Maybe plugin can be made also for Cudatext? In python API.

**Comment by shagabutdinov** [comment]
It requires (I think almost) complete rewrite of plugin. I don't have a clue how to do it for cudatext and actually not interested in it. I suggest you to write such plugin (it required me less than day to do it) or switch to sublime text. If you have any questions regarding of inner structure of this plugin or it's code you are  welcome (please, do it by email).
