### ISSUE TITLE
Error Installing Snippet Manager in Sublime Text 3

### ISSUE THREAD

**Issue by mwmoriarty** [shagabutdinov/sublime-autocompletion#9]
I am trying to install the Bootstrap 4 Snippets into Sublime Text 3 and getting this error when trying to install the Snippet manager:

> Dependency import failed; please read readme for SnippetManager plugin for installation instructions; to disable this message remove this plugin; message: No module named 'FileList'

**Comment by shagabutdinov** [comment]
* This is wrong repo to open issue about SnippetManager
* Install all dependencies recursively for this package to fix this message
